// Code generated by federate, DO NOT EDIT.
package {{.Package}};

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.config.ConfigurableListableBeanFactory;
import org.springframework.beans.factory.support.BeanDefinitionRegistry;
import org.springframework.beans.factory.support.BeanDefinitionRegistryPostProcessor;
import org.springframework.core.Ordered;
import org.springframework.core.env.Environment;

import static org.springframework.context.ConfigurableApplicationContext.ENVIRONMENT_BEAN_NAME;

@Slf4j
class FederatedBeanDefinitionConflictProcessor implements BeanDefinitionRegistryPostProcessor, Ordered {

    @Override
    public void postProcessBeanDefinitionRegistry(BeanDefinitionRegistry registry) throws BeansException {
        log.info("{} {} {}", registry.getClass().getSimpleName(), registry.getBeanDefinitionCount(), registry.getBeanDefinitionNames());
    }

    @Override
    public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
        Environment environment = beanFactory.getBean(ENVIRONMENT_BEAN_NAME, Environment.class);
        log.info("profiles: {}", environment.getActiveProfiles());
    }

    @Override
    public int getOrder() {
        return LOWEST_PRECEDENCE;
    }
}
