// Code generated by federate, DO NOT EDIT.
/**
 * BeanNameGenerator 有两个实现版本：
 *   - DefaultBeanNameGenerator：给资源文件加载bean时使用(BeanDefinitionReader)
 *   - AnnotationBeanNameGenerator：为了处理注解生成bean name的情况
 */
package {{.Package}};
