// Code generated by federate, DO NOT EDIT.
package {{.BasePackage}}.configuration;

import org.springframework.context.annotation.ImportResource;

@ImportResource(locations = "{{.SpringXml}}")
public class SpringResourcePlusLoader {
}
