package diff

import (
	"log"
	"testing"
)

func TestShowDiffLineByLine(t *testing.T) {
	tests := []struct {
		oldContent string
		newContent string
	}{
		{
			oldContent: `ab  c
ef`,
			newContent: `a1`,
		},
		{
			oldContent: `ab  c
ef`,
			newContent: `xab cd
efk
hello
bye`,
		},
		{
			oldContent: `ab  c
ef`,
			newContent: `<module>
hi
abc
d`,
		},
		{
			oldContent: `ab  c
ef`,
			newContent: `ef`,
		},
		{
			oldContent: `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by federate, DO NOT EDIT. -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>abc d
        <groupId>com.jdwl.wms</groupId>
        <version>2.3.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <version>1.0.0-SNAPSHOT</version>
    1
    2
    <artifactId>fusion-stock-inventory-parent</artifactId>
    <name>fusion-stock-inventory :: parent</name>
    <packaging>pom</packaging>

    <modules>
        <module>fusion-stock-inventory-starter</module>
    </modules>

    3

    <build>`,
			newContent: `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by federate, DO NOT EDIT. -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.jdwl.wms</groupId>
        <artifactId>wms-parent</artifactId>
        <version>2.3.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <version>1.0.0-SNAPSHOT</version>
    <artifactId>fusion-stock-inventory-parent</artifactId>
    <name>fusion-stock-inventory :: parent</name>
    <packaging>pom</packaging>

    <modules>
        <module>fusion-stock-inventory-starter</module>
        <module>fusion-stock-inventory</module>
    </modules>

    <build>`,
		},
		{
			oldContent: `abc`,
			newContent: `1ab`,
		},
	}
	for i, tc := range tests {
		log.Printf("Case[%d]\n%s\n↓\n%s", i, tc.oldContent, tc.newContent)
		ShowDiffLineByLine(tc.oldContent, tc.newContent)
	}
}

func init() {
	log.SetFlags(0)
}
